from django.urls import path

from .views import (
    CacheClearView,
    CombinedPredictView,
    CombinedCameraStartPollingView,
    CombinedCameraStopPollingView,
    CombinedCameraPollingStatusView,
    Esp32TelemetryIngestView,
    Esp32TelemetryLatestView,
    FogLatestFrameView,
    FogMJPEGStreamView,
    FogPredictView,
    FogRuntimeStatusView,
    FrontendConfigView,
    HealthView,
    PotholeLatestFrameView,
    PotholeMJPEGStreamView,
    PotholeCameraProcessView,
    FogCameraProcessView,
    PotholeCameraStartPollingView,
    PotholeCameraStopPollingView,
    PotholeCameraPollingStatusView,
    FogCameraStartPollingView,
    FogCameraStopPollingView,
    FogCameraPollingStatusView,
    PotholePredictView,
    PotholeRuntimeStatusView,
    SourceStatusView,
    SimulatePotholeAlertView,
    SimulateFogAlertView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("frontend/config/", FrontendConfigView.as_view(), name="frontend-config"),
    path("sources/status/", SourceStatusView.as_view(), name="sources-status"),
    path("cache/clear/", CacheClearView.as_view(), name="cache-clear"),
    path("telemetry/ingest/", Esp32TelemetryIngestView.as_view(), name="telemetry-ingest"),
    path("telemetry/latest/", Esp32TelemetryLatestView.as_view(), name="telemetry-latest"),
    path("fog/predict/", FogPredictView.as_view(), name="fog-predict"),
    path("fog/status/", FogRuntimeStatusView.as_view(), name="fog-status"),
    path("fog/latest-frame/", FogLatestFrameView.as_view(), name="fog-latest-frame"),
    path("fog/stream/", FogMJPEGStreamView.as_view(), name="fog-stream"),
    path("pothole/predict/", PotholePredictView.as_view(), name="pothole-predict"),
    path("pothole/camera/process/", PotholeCameraProcessView.as_view(), name="pothole-camera-process"),
    path("pothole/camera/start_poll/", PotholeCameraStartPollingView.as_view(), name="pothole-camera-start-poll"),
    path("pothole/camera/stop_poll/", PotholeCameraStopPollingView.as_view(), name="pothole-camera-stop-poll"),
    path("pothole/camera/poll_status/", PotholeCameraPollingStatusView.as_view(), name="pothole-camera-poll-status"),
    path("fog/camera/process/", FogCameraProcessView.as_view(), name="fog-camera-process"),
    path("fog/camera/start/", FogCameraStartPollingView.as_view(), name="fog-camera-start"),
    path("fog/camera/stop/", FogCameraStopPollingView.as_view(), name="fog-camera-stop"),
    path("fog/camera/poll_status/", FogCameraPollingStatusView.as_view(), name="fog-camera-poll-status"),
    path("pothole/status/", PotholeRuntimeStatusView.as_view(), name="pothole-status"),
    path("pothole/latest-frame/", PotholeLatestFrameView.as_view(), name="pothole-latest-frame"),
    path("pothole/stream/", PotholeMJPEGStreamView.as_view(), name="pothole-stream"),
    path("combined/predict/", CombinedPredictView.as_view(), name="combined-predict"),
    path("combined/camera/start/", CombinedCameraStartPollingView.as_view(), name="combined-camera-start"),
    path("combined/camera/stop/", CombinedCameraStopPollingView.as_view(), name="combined-camera-stop"),
    path("combined/camera/poll_status/", CombinedCameraPollingStatusView.as_view(), name="combined-camera-poll-status"),
    path("simulate/pothole/", SimulatePotholeAlertView.as_view(), name="simulate-pothole"),
    path("simulate/fog/", SimulateFogAlertView.as_view(), name="simulate-fog"),
]
