# Generated by Django 5.2.12 on 2026-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PotholeDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=128)),
                ("stream_id", models.CharField(blank=True, default="", max_length=128)),
                ("frame_id", models.CharField(blank=True, default="", max_length=128)),
                ("request_id", models.CharField(db_index=True, max_length=36)),
                ("mode", models.CharField(default="pothole_only", max_length=32)),
                ("pothole_count", models.PositiveIntegerField(default=0)),
                ("total_potholes", models.PositiveIntegerField(default=0)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("detections", models.JSONField(default=dict)),
                ("annotated_frame", models.BinaryField(blank=True, null=True)),
                ("frame_mime", models.CharField(default="image/jpeg", max_length=64)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_id", "-created_at"],
                        name="fog_api_pot_source__80d822_idx",
                    ),
                    models.Index(
                        fields=["stream_id", "-created_at"],
                        name="fog_api_pot_stream__593712_idx",
                    ),
                ],
            },
        ),
    ]
