# Generated by Django 5.2.12 on 2026-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fog_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="potholedetection",
            name="pothole_metrics",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
