; AEGIS-RS RSU Receiver PlatformIO Config
; Upload this to the board with MAC: 00:4B:12:30:3D:3C (on the other laptop)

[env:receiver]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
build_flags   = -D ROLE_RSU
