"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def _parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p$jzna-qm2giwgcuf2a26cu#2*l+q$3d$=5j41d3$1yz7y6^xh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "fog_api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.getenv("SQLITE_DB_PATH", str(BASE_DIR / "db.sqlite3"))),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

BACKEND_HOST = os.getenv("BACKEND_HOST", "127.0.0.1").strip() or "127.0.0.1"
BACKEND_PORT = int(os.getenv("BACKEND_PORT", "8000"))
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", f"http://{BACKEND_HOST}:{BACKEND_PORT}").strip()

FRONTEND_HOST = os.getenv("FRONTEND_HOST", "127.0.0.1").strip() or "127.0.0.1"
FRONTEND_PORT = int(os.getenv("FRONTEND_PORT", "5173"))
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", f"http://{FRONTEND_HOST}:{FRONTEND_PORT}").strip()

PHONE_POTHOLE_BASE_URL = os.getenv("PHONE_POTHOLE_BASE_URL", "").strip()
PHONE_FOG_BASE_URL = os.getenv("PHONE_FOG_BASE_URL", "").strip()

CORS_ALLOWED_ORIGINS = [
    item
    for item in {
        *(_parse_csv(os.getenv("CORS_ALLOWED_ORIGINS", ""))),
        FRONTEND_BASE_URL,
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    }
    if item
]

IDP_ROOT_DIR = BASE_DIR.parent.parent
XGBOOST_FOG_DIR = Path(os.getenv("XGBOOST_FOG_DIR", IDP_ROOT_DIR / "RTTS" / "xgboost_fog"))
XGBOOST_FOG_MODEL_PATH = Path(
    os.getenv("XGBOOST_FOG_MODEL_PATH", XGBOOST_FOG_DIR / "models" / "xgboost_fog.joblib")
)

DEHAZE_ENABLED = os.getenv("DEHAZE_ENABLED", "true").strip().lower() in {"1", "true", "yes", "on"}
DEHAZE_MODEL_PATH = Path(
    os.getenv("DEHAZE_MODEL_PATH", BASE_DIR.parent / "ffa_rtts_dehaze_fog.pt")
)
DEHAZE_IMAGE_SIZE = int(os.getenv("DEHAZE_IMAGE_SIZE", "256"))

YOLOV8_MODEL_PATH = Path(
    os.getenv(
        "YOLOV8_MODEL_PATH",
        BASE_DIR.parent / "pothole.pt",
    )
)


def _parse_path_list(value: str) -> list[Path]:
    separators = [";", ","]
    for sep in separators:
        if sep in value:
            return [Path(item.strip()) for item in value.split(sep) if item.strip()]
    value = value.strip()
    return [Path(value)] if value else []


YOLOV8_AUTO_SELECT_LATEST = os.getenv("YOLOV8_AUTO_SELECT_LATEST", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
YOLOV8_MODEL_CANDIDATES = _parse_path_list(
    os.getenv(
        "YOLOV8_MODEL_CANDIDATES",
        ";".join(
            [
                str(BASE_DIR.parent / "pothole.pt"),
                str(IDP_ROOT_DIR / "Pothole_Segmentation_YOLOv8" / "yolov8n.pt"),
            ]
        ),
    )
)
YOLOV8_CONF_THRESHOLD = float(os.getenv("YOLOV8_CONF_THRESHOLD", "0.25"))
YOLOV8_IOU_THRESHOLD = float(os.getenv("YOLOV8_IOU_THRESHOLD", "0.45"))
YOLOV8_MAX_DET = int(os.getenv("YOLOV8_MAX_DET", "100"))
YOLOV8_IMGSZ = int(os.getenv("YOLOV8_IMGSZ", "640"))
YOLOV8_IMGSZ_REALTIME = int(os.getenv("YOLOV8_IMGSZ_REALTIME", "512"))
YOLOV8_HALF = os.getenv("YOLOV8_HALF", "false").strip().lower() in {"1", "true", "yes", "on"}
YOLOV8_DEVICE = os.getenv("YOLOV8_DEVICE", "")

REALTIME_MAX_FRAME_SIDE = int(os.getenv("REALTIME_MAX_FRAME_SIDE", "960"))
REALTIME_SKIP_DEHAZE = os.getenv("REALTIME_SKIP_DEHAZE", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

POTHOLE_RECORD_TTL_SECONDS = int(os.getenv("POTHOLE_RECORD_TTL_SECONDS", "3600"))

# Stream/chunk runtime controls
STREAM_MAX_CHUNK_BYTES = int(os.getenv("STREAM_MAX_CHUNK_BYTES", str(1024 * 1024)))
STREAM_MAX_CHUNKS_PER_FRAME = int(os.getenv("STREAM_MAX_CHUNKS_PER_FRAME", "64"))
STREAM_CHUNK_TTL_SECONDS = int(os.getenv("STREAM_CHUNK_TTL_SECONDS", "120"))
SOURCE_STATUS_TTL_SECONDS = int(os.getenv("SOURCE_STATUS_TTL_SECONDS", "900"))

# Debug logging controls
PIPELINE_DEBUG_LOGS = os.getenv("PIPELINE_DEBUG_LOGS", "true").strip().lower() in {"1", "true", "yes", "on"}

# Backend-driven frontend defaults (no hardcoded IPs in frontend code)
FRONTEND_POTHOLE_SOURCE_ID = os.getenv("FRONTEND_POTHOLE_SOURCE_ID", "phone_pothole_01")
FRONTEND_FOG_SOURCE_ID = os.getenv("FRONTEND_FOG_SOURCE_ID", "phone_fog_01")
FRONTEND_STREAM_FPS = float(os.getenv("FRONTEND_STREAM_FPS", "3"))
FRONTEND_SHOW_ENDPOINTS = os.getenv("FRONTEND_SHOW_ENDPOINTS", "false").strip().lower() in {"1", "true", "yes", "on"}

# Mock data generation for dashboard demonstration
ENABLE_MOCK_DATA = os.getenv("ENABLE_MOCK_DATA", "false").strip().lower() in {"1", "true", "yes", "on"}
MOCK_DATA_INTERVAL = float(os.getenv("MOCK_DATA_INTERVAL", "2.0"))  # Generate mock frame every N seconds
MOCK_POTHOLE_PROBABILITY = float(os.getenv("MOCK_POTHOLE_PROBABILITY", "0.6"))  # 60% chance of potholes
MOCK_FOG_PROBABILITY = float(os.getenv("MOCK_FOG_PROBABILITY", "0.4"))  # 40% chance of fog
